### ISSUE TITLE
Buttons with Unimplemented Functionality

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#18]
Buttons with unimplemented functionality:
- [x] the extra Add to Map buttons (in the concept details pop-up next to Medical Specialty or Drug Used for Treatment) throw Not Implemented Exceptions
- [x] the Add Annotation buttons (in the concept map pop-up when logged in) throw Not Implemented Exceptions
- the green library buttons (in the the Library column of the concept-picking window) all have zeroes on them and don't do anything when clicked
- column names (in any list view) don't sort the results when clicked, although they still toggle between the up and down arrows

**Comment by lhannest** [comment]
The last two broken features don't currently make sense in the context of our application. I will remove the library buttons altogether from the concept view, and make the column names non-clickable so as to not confuse the user.

The column sorting features will probably never be re-implemented, whereas the library count might depending on how we rework the concept map library system.

**Comment by lhannest** [comment]
I changed my mind about the sorting and implemented a local sort of the loaded data in the relations table.
