### ISSUE TITLE
Exact match search

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#19]
When searching for concepts, exact matches are mixed in with matches that contain the search term, including matches with the search term in the middle of a word. This can cause the search results to have low relevance. One example is that when searching for "liver," the 1st result is "Drug Delivery Systems," the 4th result is "Liver dysfunction," and "Liver" doesn't appear until the 3rd page.

**Comment by lhannest** [comment]
We don't have much control over how independent beacons search their own data sources. We just need to be more clear with our specification on how searches should be executed. I'll make note of this issue elsewhere.
