### ISSUE TITLE
Never-ending search results

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#20]
When searching for a concept, results from certain beacons seem to be repeating in an endless(?) loop, which makes the search results seem infinite. In particular, results from Monarch and String-db.org wrapper results do this. Additionally, the repeating results seem to appear no matter what Semantic Group filter is selected (although they do obey the text filter).

**Comment by lhannest** [comment]
This is a flaw with the beacons, not our application. @goodb 

It looks like these beacons just return all the data they have, without paging it. E.g., the following queries return the same data:
http://52.14.14.106:8090/api/concepts?keywords=diabetes&pageNumber=1
http://52.14.14.106:8090/api/concepts?keywords=diabetes&pageNumber=2

In the future we should automate testing for beacons properly paging their data.

**Comment by goodb** [comment]
Yup.  these don't actually implement the paging function.  It will be a challenge to consider how to  balance beacon testing / advice with increasing the tolerance of the kb application to their errors.  

Certainly thumbs up on Beacon testing when they are first loaded and at some periodic interval (e.g. at each application load or at a user or admin's request - depending on how long it takes).

**Comment by lhannest** [comment]
Closing this issue, beacons should be expected to implement pagination if they are to be used with TKBio. @RichardBruskiewich let me know if you disagree.
