### ISSUE TITLE
Differences in this version

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#21]
These are some observations of functionality that behaved differently in the old version. They may or may not be bugs:
- when evidence is opened in the Reference tab, the "Search Reference ID" box is no longer pre-populated with the article's ID
- filtering concepts by Semantic Group still leaves some results with a different group in the Semantic Group column
- switching to the Relations tab from one of the other tabs causes its contents to be reloaded

**Comment by lhannest** [comment]
The semantic group filter issue is because some of the beacons haven't developed this feature, and it is not a problem with our application.
