### ISSUE TITLE
Odd results in search

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/tkbio#3]
Searching for stress disorder:

![image](https://cloud.githubusercontent.com/assets/50745/26369306/22ae4702-3fa9-11e7-9bca-2a39f030adce.png)

Note I seem to have all beacons selected:

![image](https://cloud.githubusercontent.com/assets/50745/26369337/41f78614-3fa9-11e7-84ff-b52a1a194607.png)

In a distributed system we should be resilient to some beacons returning odd results. However, we still need to provide some kind of recommendations as to search behavior.

Also, we need to be able to see which beacon each search result is coming from

**Comment by goodb** [comment]
I saw something similar.  It seems that its looking for "stress"  and "disorder"  instead of "stress disorder" .  I think this a bug in the API definition: "a (urlencoded) space delimited set of keywords or substrings against which to match concept names and synonyms"   

Need to define how people should search for multi-string terms.

**Comment by RichardBruskiewich** [comment]
Yes, this issue relates to knowledge beacon implementation of the /concepts API call. Perhaps we need to clarify the intended semantics of the search, that hits should be returned in order of maximum number of keyword hits.
We've implemented a fix in the reference-beacon (http://beacon.medgeninformatics.net) to give this behaviour (works!) but other beacons will need to review this.
On the second issue of showing which beacon returns which research results, we are now working on that. We'll add a column for the CURIE (which will give the user feedback on beacon source and object identity) as well as, description (and fix a bug with semgroups). This should improve the interpretation of the results of the concept by text search. We'll deploy this as soon as it works!

**Comment by cmungall** [comment]
> Need to define how people should search for multi-string terms

It would be cool to aggregate results of different NER annotators.
