### ISSUE TITLE
Concept map export not working

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#31]
Exporting maps (in any format) doesn't produce a file. In Safari, nothing happens at all. In Chrome, the download has the message:
> dl
> Failed - Network error

Telling Chrome to resume the download changes the message to:
> dl
> Failed - No file

**Comment by lhannest** [comment]
Oddly firefox does not have this problem.

**Comment by lhannest** [comment]
If we want to come back to this in the future: https://vaadin.com/forum#!/thread/11099170
