### ISSUE TITLE
Concept map loading not working

### ISSUE THREAD

**Issue by meera-gd** [NCATS-Tangerine/tkbio#34]
In resolving issue #31, statementId's were adding to the graph. But concept maps saved (or exported) before that don't have the statementId field. This causes an error to be thrown when trying to add old concept maps to the graph.

**Comment by lhannest** [comment]
I'm labeling as wontfix and closing this issue. We can clean up old concept maps if we want, but there's no reason to change TKBio to handle this.

@RichardBruskiewich let me know if you disagree.
