### ISSUE TITLE
provenance of objects and relationships should be clearer

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/tkbio#4]
![image](https://cloud.githubusercontent.com/assets/50745/26369508/bd754af6-3fa9-11e7-829d-2dfafe9b943b.png)

 - It should be possible to see the ID for the objects in the blackboard and in the table.
 - The source for the relationships should be visible

**Comment by lhannest** [comment]
@cmungall We have added the beacon source to the columns for all data.

![printscreen](https://user-images.githubusercontent.com/12465184/29288567-0fce2a9a-80ee-11e7-92be-eb9d0529c9ad.png)


@RichardBruskiewich  For displaying ID's, what if we had that show up for tool tips? We could also show other essential data, like semantic type and if the concept is a gene then its taxon. That would be a good solution to https://github.com/NCATS-Tangerine/tkbio/issues/41 as well.

**Comment by RichardBruskiewich** [comment]
Although not yet perfect, we now have concept cliques. In the relations table, the subject and object concepts now have beacon source, clique id and original id displayed for each. Also, the concept details popups summarize the aliases (albeit, still somewhat sloppily). Nonetheless, we'll close this issue for now given the progress made here.
