### ISSUE TITLE
Going to References Tab from Evidence Tab of Monarch Beacon causes failure to display References

### ISSUE THREAD

**Issue by bordercases** [NCATS-Tangerine/tkbio#47]
Going to References Tab From Evidence Tab of a Relation from the Monarch Beacon (in this case, "GCK") seems to cause the following error:

"The statement id is not a curie and could not be parsed at ReferenceView.GetUri... (81)"

It seems to work fine for nDEX Bio concept of the same name, but not another Monarch Beacon Concept ("NM_000799.2(EPO):c.-1306C>A").

**Comment by bordercases** [comment]
Failure also seems to occur with WikiData beacon

**Comment by lhannest** [comment]
UI is being revised, we no longer have an evidence tab.
