### ISSUE TITLE
Beacon "Record Logs" button works to bring up a logs page, but the result set is always empty?

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/tkbio#57]
The TKBIO 'Beacons" menu brings up a dialog box with a "Record Logs" check box and "View Logs" button.

Even after checking the box, and doing some queries, the "View Logs"  button works to bring back a page, but there are no results (i.e. the JSON array is empty "[]")

**Comment by RichardBruskiewich** [comment]
Not *always* empty... sometimes, something is sent back, but not consistently

**Comment by RichardBruskiewich** [comment]
Further investigation suggests that perhaps the bug is in the underlying beacon aggregator code, so perhaps, review that first.

**Comment by lhannest** [comment]
Closing issue here, opening a new one in KBA repo.
